config/routes.rb
Rashka::Application.routes.draw do

  post "admin/login"

  root 'pages#index'

  match 'admin' => 'admin#index', via: :get

  resources :news

  resources :reasons do
    collection do
      get 'get_one_random'
      get 'get_three_random'
    end
  end

  match 'stats' => 'stats#index', via: :get
  match 'stats/evacuate' => 'stats#evacuate', via: :post
  match 'stats/vk_post' => 'stats#vk_post', via: :post
  match 'stats/fb_post' => 'stats#fb_post', via: :post
  match 'stats/tw_post' => 'stats#tw_post', via: :post
  match 'stats/bl_post' => 'stats#bl_post', via: :post

end

app/models/reason.rb
# Причины
# @example
#   #<Reason id: 2, text: "Страной правят геи", popularity: 12313, created_at: "2014-02-15 11:03:31", updated_at: "2014-02-17 07:32:35">
class Reason < ActiveRecord::Base
  include Paginated
  scope :random_one, -> {order("RANDOM()").select(:text).first}
  scope :random_three, -> {order("RANDOM()").limit(3)}
  scope :popular, -> {order(:popularity, :updated_at).reverse_order}

  scope :find_downcase, -> (downcase_text) {where('lower(text) like ?', "%#{downcase_text}%")}

  validates :text, :uniqueness => {:case_sensitive => false, :message => "такая причина уже есть"}
  validates_length_of :text, :minimum => 2, :maximum => 81, :message => "должен быть длиной от 2 до 81 символа"


  # Либо сохраняет новую причину, либо увеличивает статистику популярности у существующей
  # @note Вызывается при нажатии по соц кнопке
  # @example
  #   Reason.first.try_to_save
  #
  # @see StatsController#update_reason
  def try_to_save
    downcase_text = self.text.mb_chars.downcase.to_s
    reason = Reason.find_downcase(downcase_text)
    reason.present? ? reason.first.increase_popularity : self.save
  end


  # Увеличивает статистику популярности у причины
  # @note Вызывается при нажатии по соц кнопке
  # @example
  #   Reason.increase_popularity
  #
  # @see Reason#try_to_save
  def increase_popularity
    self.update(popularity: self.popularity + 1)
  end
end

app/controllers/reasons_controller.rb
#Методы причин
class ReasonsController < ApplicationController
  include Admin

  before_action :allow_access?, only: [:index, :show, :edit, :new, :create, :update, :destroy]

  layout 'admin', except: [:get_one_random, :get_three_random]


  # Выводит текст случайной причины
  # @note GET /reasons/get_one_random
  # @note Вызывается при нажатии по кнопке "подсказать" в окошке рассказать
  # @see Reason
  def get_one_random
    @reason = Reason.random_one.text

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render :layout => false }
    end
  end


  # Выводит текст трех случайных причин
  # @note GET /reasons/get_three_random
  # @note Вызывается каждые 10 сек в блоке причин на главной
  # @see Reason
  def get_three_random
    @reasons = Reason.random_three

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render :layout => false }
    end
  end

  def index
    @reasons = Reason.popular.paginated(params[:page], 50)
  end

  def show
    @reason = Reason.find(params[:id])
  end

  def edit
    @reason = Reason.find(params[:id])
  end

  def new
    @reason = Reason.new
  end

  def create
    @reason = Reason.new(reason_params)

    respond_to do |format|
      if @reason.save
        notice = {class: "alert-success", value: 'Успешно добавил причину.' }
        format.html { redirect_to @reason, notice: notice }
      else
        notice = {class: "alert-danger", value: 'Ошибка при добавлении.' }
        format.html { render :new, notice: notice }
      end
    end
  end

  def update
    @reason = Reason.find(params[:id])

    respond_to do |format|
      if @reason.update_attributes(reason_params)
        notice = {class: "alert-success", value: 'Успешно обновил причину.' }
        format.html { redirect_to @reason, notice: notice }
      else
        notice = {class: "alert-danger", value: 'Ошибка при редактировании.' }
        format.html { render :edit, notice: notice }
      end
    end
  end

  def destroy
    @reason = Reason.find(params[:id])
    @reason.destroy

    respond_to do |format|
      notice = {class: "alert-danger", value: 'Успешно удалил причину.' }
      format.html { redirect_to reasons_path, notice: notice }
    end
  end

  private

  def reason_params
    params.require(:reason).permit(:text)
  end
end

app/views/reasons/_form.haml
= form_for(reason) do |f|
  - if reason.errors.any?
    #error_explanation.alert.alert-danger
      %h2
        = reason.errors.count
        = Russian.p(reason.errors.count, "ошибка", "ошибки", "ошибок")
      %ul
        - reason.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :text, "Текст"
    = f.text_area :text, {class: "form-control"}
  .form-group
    = f.label :popularity, "Популярность"
    = f.number_field :popularity, {class: "form-control"}
  .actions
    = f.submit "Бдыщ", {class: "btn btn-default"}

app/views/reasons/_menu.html.haml
-cache do
  %nav.navbar.navbad-default
    .container-fluid
      %ul.nav.navbar-nav
        %li
          =link_to "На сайт", root_path
        %li
          =link_to "Назад в админку", admin_path
        %li
          =link_to "Список причин", reasons_path
        %li
          =link_to "Новая причина", new_reason_path

app/views/reasons/_pagination.haml
= render @reasons
= will_paginate @reasons, :param_name => 'reasons_page', :class => "pagination hidden"

app/views/reasons/_reason.haml
-cache reason do
  %article.reason
    %p.text
      =reason.text
    .share_reason{title: "Поделиться с друзьями"}
      Рассказать

app/views/reasons/_reasons_modal.haml
-cache do
  %h3
    Я валю из рашки, потому что:
#reasons_pagination
  = render 'reasons/pagination'

app/views/reasons/edit.html.haml
=render 'menu'

.container-fluid
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-6
      %h1
        Редактирование причины

      =render 'form', :reason => @reason

app/views/reasons/get_one_random.js.erb
var reason_field = $("#reason_field"),
  get_random_container = $("#get_random_container");
reason_field.val("<%= @reason %>");
reason_field.trigger("change");

get_random_container.removeClass("loading");
get_random_container.find("img").addClass("hidden");

app/views/reasons/get_random.js.erb
var reason_field = $("#reason_field");
reason_field.val("<%= @reason %>");
reason_field.trigger("change");

app/views/reasons/get_three_random.js.erb
$("#reasons_container .reload_container").html("<%= j render @reasons %>");

app/views/reasons/index.html.haml
=render 'menu'

.container-fluid
  .row
    .col-md-10
      %h1
        Все причины:
      .table-responsive
        %table.table.table-hover
          %thead
            %tr
              %th
                Текст
              %th
                Популярность
              %th
                Обновлено
              %th
                удалить
          -@reasons.each do |reason|
            -cache reason do
              %tbody
                %tr
                  %td
                    =reason.text
                  %td
                    =reason.popularity
                  %td
                    =reason.updated_at
                  %td
                    =link_to "редактировать", edit_reason_path(reason.id)
                  %td
                    =link_to "удалить", reason, :data => {confirm: 'Точно удалить? Восстановить никак'}, method: :delete


      = will_paginate @reasons

app/views/reasons/index_admin.html.haml
=render 'menu'

.container-fluid
  .row
    .col-md-10
      %h1
        Все причины:
      .table-responsive
        %table.table.table-hover
          %thead
            %tr
              %th
                Текст
              %th
                Популярность
              %th
                Обновлено
              %th
                удалить
          -@reasons.each do |reason|
            -cache reason do
              %tbody
                %tr
                  %td
                    =reason.text
                  %td
                    =reason.popularity
                  %td
                    =reason.updated_at
                  %td
                    =link_to "редактировать", edit_reason_path(reason.id)
                  %td
                    =link_to "удалить", reason, :data => {confirm: 'Точно удалить? Восстановить никак'}, method: :delete

app/views/reasons/new.html.haml
=render 'menu'

.container-fluid
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-6
      %h1
        Создание причины

      =render 'form', :reason => @reason

app/views/reasons/show.html.haml
=render 'menu'

.container-fluid
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-6
      -cache @reason do
        %h1
          Причина #{params[:id]}
        %p
          %b
            Текст:
          =@reason.text
        %p
          %b
            Популярность:
          =@reason.popularity