config/routes.rb
Rashka::Application.routes.draw do

  post "admin/login"

  root 'pages#index'

  match 'admin' => 'admin#index', via: :get

  resources :news

  resources :reasons do
    collection do
      get 'get_one_random'
      get 'get_three_random'
    end
  end

  match 'stats' => 'stats#index', via: :get
  match 'stats/evacuate' => 'stats#evacuate', via: :post
  match 'stats/vk_post' => 'stats#vk_post', via: :post
  match 'stats/fb_post' => 'stats#fb_post', via: :post
  match 'stats/tw_post' => 'stats#tw_post', via: :post
  match 'stats/bl_post' => 'stats#bl_post', via: :post

end

app/models/news.rb
# Новости
# @example
#   #<News id: 12, title: "Пыщь пыщь ололо", text: "Всё плохо", link: "http://brandonhilkert.com/", created_at: "2014-02-16 19:51:09", updated_at: "2014-02-16 19:51:09">
class News < ActiveRecord::Base
  include Paginated

  # default_scope {order(updated_at: :desc)}

  validates_presence_of :title, :text, :link, message: "нужно чем-то заполнить"
  validates_uniqueness_of :text, :title, :link, :message => "не должно повторяться в другой новости"
  validates_length_of :text, :title, :minimum => 2, :maximum => 150, :message => "должен быть длиной от 2 до 150 символов"
  validates_length_of :link, :minimum => 2, :maximum => 255, :message => "должен быть длиной до 255 символов, иначе придется менять тип поля"
end

app/controllers/news_controller.rb
#Админские методы новостей
class NewsController < ApplicationController
  include Admin

  before_action :allow_access?, only: [:index, :show, :edit, :new, :create, :update, :destroy]

  layout 'admin'

  def index
    @news = News.paginated(params[:page], 25)
  end

  def show
    @one_news = News.find(params[:id])
  end

  def edit
    @one_news = News.find(params[:id])
  end

  def new
    @one_news = News.new
  end

  def create
    @one_news = News.new(news_params)

    respond_to do |format|
      if @one_news.save
        notice = {class: "alert-success", value: 'Успешно обновил новость.' }
        format.html { redirect_to @one_news, notice: notice }
      else
        notice = {class: "alert-danger", value: 'Ошибка при добавлении.' }
        format.html { render :new, notice: notice }
      end
    end
  end

  def update
    @one_news = News.find(params[:id])

    respond_to do |format|
      if @one_news.update_attributes(news_params)
        notice = {class: "alert-success", value: 'Успешно обновил новость.' }

        format.html { redirect_to @one_news, notice: notice }
      else
        notice = {class: "alert-danger", value: 'Ошибка при редактировании.' }

        format.html { render :edit, notice: notice }
      end
    end
  end

  def destroy
    @one_news = News.find(params[:id])
    @one_news.destroy

    respond_to do |format|
      notice = {class: "alert-danger", value: 'Успешно удалил новость.' }
      format.html { redirect_to news_index_path, notice: notice }
    end
  end

  private

  def news_params
    params.require(:news).permit(:title, :text, :link)
  end
end

app/views/news/_form.haml
= form_for(one_news) do |f|
  - if one_news.errors.any?
    #error_explanation.alert.alert-danger
      %h2
        = one_news.errors.count
        = Russian.p(one_news.errors.count, "ошибка", "ошибки", "ошибок")
      %ul
        - one_news.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :title, "Заголовок"
    = f.text_field :title, {class: "form-control"}
  .form-group
    = f.label :text, "Текст"
    = f.text_area :text, {class: "form-control"}
  .form-group
    = f.label :link, "Ссылка"
    = f.text_field :link, {class: "form-control"}
  .actions
    = f.submit "Бдыщ", {class: "btn btn-default"}

app/views/news/_menu.html.haml
-cache do
  %nav.navbar.navbad-default
    .container-fluid
      %ul.nav.navbar-nav
        %li
          =link_to "На сайт", root_path
        %li
          =link_to "Назад в админку", admin_path
        %li
          =link_to "Список новостей", news_index_path
        %li
          =link_to "Новая новость", new_news_path

app/views/news/_news.haml
-cache news do
  %article.news_article{:data => {:link => news.link}}
    %h4
      =news.title
    %p
      =news.text

app/views/news/edit.html.haml
=render 'menu'

.container-fluid
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-6
      %h1
        Редактирование новости

      =render 'form', :one_news => @one_news

app/views/news/index.html.haml
=render 'menu'

.container-fluid
  .row
    .col-md-10
      %h1
        Все новости:
      .table-responsive
        %table.table.table-hover
          %thead
            %tr
              %th
                Заголовок
              %th
                Текст
              %th
                Ссылка
              %th
                Обновлено
              %th
                редактировать
              %th
                удалить
          -@news.each do |news|
            -cache news do
              %tbody
                %tr
                  %td
                    =news.title
                  %td
                    =news.text
                  %td
                    =news.link
                  %td
                    =news.updated_at
                  %td
                    =link_to "редактировать", edit_news_path(news.id)
                  %td
                    =link_to "удалить", news, :data => {confirm: 'Точно удалить? Восстановить никак'}, method: :delete

      = will_paginate @news

app/views/news/index_admin.html.haml
=render 'menu'

.container-fluid
  .row
    .col-md-10
      %h1
        Все новости:
      .table-responsive
        %table.table.table-hover
          %thead
            %tr
              %th
                Заголовок
              %th
                Текст
              %th
                Ссылка
              %th
                Обновлено
              %th
                редактировать
              %th
                удалить
          -@news.each do |news|
            -cache news do
              %tbody
                %tr
                  %td
                    =news.title
                  %td
                    =news.text
                  %td
                    =news.link
                  %td
                    =news.updated_at
                  %td
                    =link_to "редактировать", edit_news_path(news.id)
                  %td
                    =link_to "удалить", news, :data => {confirm: 'Точно удалить? Восстановить никак'}, method: :delete

app/views/news/new.html.haml
=render 'menu'

.container-fluid
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-6
      %h1
        Создание новости

      =render 'form', :one_news => @one_news

app/views/news/show.html.haml
=render 'menu'

.container-fluid
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-6
      -cache @one_news do
        %h1
          Новость #{params[:id]}
        %p
          %b
            Заголовок:
          =@one_news.title
        %p
          %b
            Текст:
          =@one_news.text
        %p
          %b
            Ссылка:
          =@one_news.link