config/routes.rb
Rashka::Application.routes.draw do

  post "admin/login"

  root 'pages#index'

  match 'admin' => 'admin#index', via: :get

  resources :news

  resources :reasons do
    collection do
      get 'get_one_random'
      get 'get_three_random'
    end
  end

  match 'stats' => 'stats#index', via: :get
  match 'stats/evacuate' => 'stats#evacuate', via: :post
  match 'stats/vk_post' => 'stats#vk_post', via: :post
  match 'stats/fb_post' => 'stats#fb_post', via: :post
  match 'stats/tw_post' => 'stats#tw_post', via: :post
  match 'stats/bl_post' => 'stats#bl_post', via: :post

end

app/views/pages/share/_brainlook.haml
-cache do
  #brainlook_container{data: {link: "http://brainlook.org/opinions/publish/"}}
    %h3
      Хочешь найти попутчиков?
    .brainlook
    %p
      Опубликуй причину эвакуации в виде мнения на Brainlook! В этой энциклопедии мнений ты узнаешь, что объединяет согласных и не согласных с тобой.

app/views/pages/share/_create_story.haml
#create_story
  %h3
    Я валю из рашки, потому что:
  %div
    =text_area_tag "reason", @one_reason, {id: "reason_field", class: "form-control"}
    -cache do
      #get_random_container
        =link_to "Подсказать?", get_one_random_reasons_path, {:remote => true, :title => "Подсказать причину"}
        =image_tag 'loader.svg', {class: "hidden"}
      %p#reason_text_counter{title: "Сколько осталось символов"}
        80

app/views/pages/share/_share_modal.haml
= render 'pages/share/create_story'
= render 'pages/share/social_container'
= render 'pages/share/brainlook'

app/views/pages/share/_social_container.haml
-cache do
  #social_container.text-center
    =social_btn("vk", "Рассказать", "http://vkontakte.ru/share.php?url=http://valiizrashki.ru/")
    =social_btn("fb", "Поделиться", "")
    =social_btn("tw", "Твитнуть", "https://twitter.com/intent/tweet?url=http://valiizrashki.ru/")